HOSTS:
  el10-default:
    platform: el-10-x86_64
    ip: 127.0.0.1
    image: rockylinux:10
    hypervisor: docker
    docker_cmd: /usr/sbin/sshd -D -e
    docker_image_commands:
      - dnf install -y cronie initscripts wget iproute
CONFIG:
  log_level: verbose
  type: foss