HOSTS:
  ubuntu24-default:
    platform: ubuntu-24.04-x86_64
    ip: 127.0.0.1
    image: ubuntu:24.04
    hypervisor: docker
    docker_cmd: /usr/sbin/sshd -D -e
    docker_image_commands:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install -y cron openssh-server wget
CONFIG:
  log_level: verbose
  type: foss